-- Add granular feature modules matching role permission keys
WITH new_features(key, name, description, category, sort_order, is_active) AS (
  VALUES
    ('dashboard', 'Dashboard', 'Granular subscription gate for permission: dashboard', 'general', 1000, true),
    ('dashboard-view', 'Dashboard View', 'Granular subscription gate for permission: dashboard-view', 'general', 1001, true),
    ('construction', 'Construction', 'Granular subscription gate for permission: construction', 'construction', 1002, true),
    ('construction-dashboard', 'Construction Dashboard', 'Granular subscription gate for permission: construction-dashboard', 'construction', 1003, true),
    ('construction-dashboard-view', 'Construction Dashboard View', 'Granular subscription gate for permission: construction-dashboard-view', 'construction', 1004, true),
    ('jobs', 'Jobs', 'Granular subscription gate for permission: jobs', 'construction', 1005, true),
    ('jobs-view', 'Jobs View', 'Granular subscription gate for permission: jobs-view', 'construction', 1006, true),
    ('jobs-add', 'Jobs Add', 'Granular subscription gate for permission: jobs-add', 'construction', 1007, true),
    ('jobs-edit', 'Jobs Edit', 'Granular subscription gate for permission: jobs-edit', 'construction', 1008, true),
    ('jobs-delete', 'Jobs Delete', 'Granular subscription gate for permission: jobs-delete', 'construction', 1009, true),
    ('jobs-tab-details', 'Jobs Tab Details', 'Granular subscription gate for permission: jobs-tab-details', 'construction', 1010, true),
    ('jobs-view-details', 'Jobs View Details', 'Granular subscription gate for permission: jobs-view-details', 'construction', 1011, true),
    ('jobs-edit-details', 'Jobs Edit Details', 'Granular subscription gate for permission: jobs-edit-details', 'construction', 1012, true),
    ('jobs-tab-committed-costs', 'Jobs Tab Committed Costs', 'Granular subscription gate for permission: jobs-tab-committed-costs', 'construction', 1013, true),
    ('jobs-view-committed-costs', 'Jobs View Committed Costs', 'Granular subscription gate for permission: jobs-view-committed-costs', 'construction', 1014, true),
    ('jobs-edit-committed-costs', 'Jobs Edit Committed Costs', 'Granular subscription gate for permission: jobs-edit-committed-costs', 'construction', 1015, true),
    ('jobs-tab-budget', 'Jobs Tab Budget', 'Granular subscription gate for permission: jobs-tab-budget', 'construction', 1016, true),
    ('jobs-view-budget', 'Jobs View Budget', 'Granular subscription gate for permission: jobs-view-budget', 'construction', 1017, true),
    ('jobs-edit-budget', 'Jobs Edit Budget', 'Granular subscription gate for permission: jobs-edit-budget', 'construction', 1018, true),
    ('jobs-tab-forecasting', 'Jobs Tab Forecasting', 'Granular subscription gate for permission: jobs-tab-forecasting', 'construction', 1019, true),
    ('jobs-view-forecasting', 'Jobs View Forecasting', 'Granular subscription gate for permission: jobs-view-forecasting', 'construction', 1020, true),
    ('jobs-edit-forecasting', 'Jobs Edit Forecasting', 'Granular subscription gate for permission: jobs-edit-forecasting', 'construction', 1021, true),
    ('jobs-tab-plans', 'Jobs Tab Plans', 'Granular subscription gate for permission: jobs-tab-plans', 'construction', 1022, true),
    ('jobs-view-plans', 'Jobs View Plans', 'Granular subscription gate for permission: jobs-view-plans', 'construction', 1023, true),
    ('jobs-upload-plans', 'Jobs Upload Plans', 'Granular subscription gate for permission: jobs-upload-plans', 'construction', 1024, true),
    ('jobs-delete-plans', 'Jobs Delete Plans', 'Granular subscription gate for permission: jobs-delete-plans', 'construction', 1025, true),
    ('jobs-tab-rfis', 'Jobs Tab Rfis', 'Granular subscription gate for permission: jobs-tab-rfis', 'construction', 1026, true),
    ('jobs-view-rfis', 'Jobs View Rfis', 'Granular subscription gate for permission: jobs-view-rfis', 'construction', 1027, true),
    ('jobs-create-rfis', 'Jobs Create Rfis', 'Granular subscription gate for permission: jobs-create-rfis', 'construction', 1028, true),
    ('jobs-edit-rfis', 'Jobs Edit Rfis', 'Granular subscription gate for permission: jobs-edit-rfis', 'construction', 1029, true),
    ('jobs-delete-rfis', 'Jobs Delete Rfis', 'Granular subscription gate for permission: jobs-delete-rfis', 'construction', 1030, true),
    ('jobs-tab-billing', 'Jobs Tab Billing', 'Granular subscription gate for permission: jobs-tab-billing', 'construction', 1031, true),
    ('jobs-view-billing', 'Jobs View Billing', 'Granular subscription gate for permission: jobs-view-billing', 'construction', 1032, true),
    ('jobs-edit-billing', 'Jobs Edit Billing', 'Granular subscription gate for permission: jobs-edit-billing', 'construction', 1033, true),
    ('jobs-approve-sov', 'Jobs Approve Sov', 'Granular subscription gate for permission: jobs-approve-sov', 'construction', 1034, true),
    ('jobs-create-draws', 'Jobs Create Draws', 'Granular subscription gate for permission: jobs-create-draws', 'construction', 1035, true),
    ('jobs-send-draws', 'Jobs Send Draws', 'Granular subscription gate for permission: jobs-send-draws', 'construction', 1036, true),
    ('jobs-tab-photos', 'Jobs Tab Photos', 'Granular subscription gate for permission: jobs-tab-photos', 'construction', 1037, true),
    ('jobs-tab-photos-albums', 'Jobs Tab Photos Albums', 'Granular subscription gate for permission: jobs-tab-photos-albums', 'construction', 1038, true),
    ('jobs-photos-create-albums', 'Jobs Photos Create Albums', 'Granular subscription gate for permission: jobs-photos-create-albums', 'construction', 1039, true),
    ('jobs-photos-edit-albums', 'Jobs Photos Edit Albums', 'Granular subscription gate for permission: jobs-photos-edit-albums', 'construction', 1040, true),
    ('jobs-photos-delete-albums', 'Jobs Photos Delete Albums', 'Granular subscription gate for permission: jobs-photos-delete-albums', 'construction', 1041, true),
    ('jobs-tab-photos-photos', 'Jobs Tab Photos Photos', 'Granular subscription gate for permission: jobs-tab-photos-photos', 'construction', 1042, true),
    ('jobs-view-photo-album', 'Jobs View Photo Album', 'Granular subscription gate for permission: jobs-view-photo-album', 'construction', 1043, true),
    ('jobs-upload-photos', 'Jobs Upload Photos', 'Granular subscription gate for permission: jobs-upload-photos', 'construction', 1044, true),
    ('jobs-delete-photos', 'Jobs Delete Photos', 'Granular subscription gate for permission: jobs-delete-photos', 'construction', 1045, true),
    ('jobs-markup-photos', 'Jobs Markup Photos', 'Granular subscription gate for permission: jobs-markup-photos', 'construction', 1046, true),
    ('jobs-tab-files', 'Jobs Tab Files', 'Granular subscription gate for permission: jobs-tab-files', 'construction', 1047, true),
    ('jobs-view-filing-cabinet', 'Jobs View Filing Cabinet', 'Granular subscription gate for permission: jobs-view-filing-cabinet', 'construction', 1048, true),
    ('jobs-upload-files', 'Jobs Upload Files', 'Granular subscription gate for permission: jobs-upload-files', 'construction', 1049, true),
    ('jobs-delete-files', 'Jobs Delete Files', 'Granular subscription gate for permission: jobs-delete-files', 'construction', 1050, true),
    ('subcontracts', 'Subcontracts', 'Granular subscription gate for permission: subcontracts', 'construction', 1051, true),
    ('subcontracts-view', 'Subcontracts View', 'Granular subscription gate for permission: subcontracts-view', 'construction', 1052, true),
    ('subcontracts-add', 'Subcontracts Add', 'Granular subscription gate for permission: subcontracts-add', 'construction', 1053, true),
    ('subcontracts-edit', 'Subcontracts Edit', 'Granular subscription gate for permission: subcontracts-edit', 'construction', 1054, true),
    ('subcontracts-delete', 'Subcontracts Delete', 'Granular subscription gate for permission: subcontracts-delete', 'construction', 1055, true),
    ('purchase-orders', 'Purchase Orders', 'Granular subscription gate for permission: purchase-orders', 'construction', 1056, true),
    ('purchase-orders-view', 'Purchase Orders View', 'Granular subscription gate for permission: purchase-orders-view', 'construction', 1057, true),
    ('purchase-orders-add', 'Purchase Orders Add', 'Granular subscription gate for permission: purchase-orders-add', 'construction', 1058, true),
    ('purchase-orders-edit', 'Purchase Orders Edit', 'Granular subscription gate for permission: purchase-orders-edit', 'construction', 1059, true),
    ('purchase-orders-delete', 'Purchase Orders Delete', 'Granular subscription gate for permission: purchase-orders-delete', 'construction', 1060, true),
    ('construction-reports', 'Construction Reports', 'Granular subscription gate for permission: construction-reports', 'construction', 1061, true),
    ('construction-reports-view', 'Construction Reports View', 'Granular subscription gate for permission: construction-reports-view', 'construction', 1062, true),
    ('cost-codes', 'Cost Codes', 'Granular subscription gate for permission: cost-codes', 'construction', 1063, true),
    ('cost-codes-view', 'Cost Codes View', 'Granular subscription gate for permission: cost-codes-view', 'construction', 1064, true),
    ('cost-codes-add', 'Cost Codes Add', 'Granular subscription gate for permission: cost-codes-add', 'construction', 1065, true),
    ('cost-codes-edit', 'Cost Codes Edit', 'Granular subscription gate for permission: cost-codes-edit', 'construction', 1066, true),
    ('cost-codes-delete', 'Cost Codes Delete', 'Granular subscription gate for permission: cost-codes-delete', 'construction', 1067, true),
    ('delivery-tickets', 'Delivery Tickets', 'Granular subscription gate for permission: delivery-tickets', 'construction', 1068, true),
    ('delivery-tickets-view', 'Delivery Tickets View', 'Granular subscription gate for permission: delivery-tickets-view', 'construction', 1069, true),
    ('delivery-tickets-add', 'Delivery Tickets Add', 'Granular subscription gate for permission: delivery-tickets-add', 'construction', 1070, true),
    ('delivery-tickets-edit', 'Delivery Tickets Edit', 'Granular subscription gate for permission: delivery-tickets-edit', 'construction', 1071, true),
    ('receipts', 'Receipts', 'Granular subscription gate for permission: receipts', 'accounting', 1072, true),
    ('receipts-upload', 'Receipts Upload', 'Granular subscription gate for permission: receipts-upload', 'accounting', 1073, true),
    ('receipts-upload-access', 'Receipts Upload Access', 'Granular subscription gate for permission: receipts-upload-access', 'accounting', 1074, true),
    ('receipts-uncoded', 'Receipts Uncoded', 'Granular subscription gate for permission: receipts-uncoded', 'accounting', 1075, true),
    ('receipts-uncoded-view', 'Receipts Uncoded View', 'Granular subscription gate for permission: receipts-uncoded-view', 'accounting', 1076, true),
    ('receipts-code', 'Receipts Code', 'Granular subscription gate for permission: receipts-code', 'accounting', 1077, true),
    ('receipts-coded', 'Receipts Coded', 'Granular subscription gate for permission: receipts-coded', 'accounting', 1078, true),
    ('receipts-coded-view', 'Receipts Coded View', 'Granular subscription gate for permission: receipts-coded-view', 'accounting', 1079, true),
    ('receipts-edit', 'Receipts Edit', 'Granular subscription gate for permission: receipts-edit', 'accounting', 1080, true),
    ('receipts-delete', 'Receipts Delete', 'Granular subscription gate for permission: receipts-delete', 'accounting', 1081, true),
    ('receipt-reports', 'Receipt Reports', 'Granular subscription gate for permission: receipt-reports', 'accounting', 1082, true),
    ('receipt-reports-view', 'Receipt Reports View', 'Granular subscription gate for permission: receipt-reports-view', 'accounting', 1083, true),
    ('receivables', 'Receivables', 'Granular subscription gate for permission: receivables', 'accounting', 1084, true),
    ('receivables-dashboard', 'Receivables Dashboard', 'Granular subscription gate for permission: receivables-dashboard', 'accounting', 1085, true),
    ('receivables-dashboard-view', 'Receivables Dashboard View', 'Granular subscription gate for permission: receivables-dashboard-view', 'accounting', 1086, true),
    ('customers', 'Customers', 'Granular subscription gate for permission: customers', 'accounting', 1087, true),
    ('customers-view', 'Customers View', 'Granular subscription gate for permission: customers-view', 'accounting', 1088, true),
    ('customers-add', 'Customers Add', 'Granular subscription gate for permission: customers-add', 'accounting', 1089, true),
    ('customers-edit', 'Customers Edit', 'Granular subscription gate for permission: customers-edit', 'accounting', 1090, true),
    ('customers-delete', 'Customers Delete', 'Granular subscription gate for permission: customers-delete', 'accounting', 1091, true),
    ('ar-invoices', 'Ar Invoices', 'Granular subscription gate for permission: ar-invoices', 'accounting', 1092, true),
    ('ar-invoices-view', 'Ar Invoices View', 'Granular subscription gate for permission: ar-invoices-view', 'accounting', 1093, true),
    ('ar-invoices-add', 'Ar Invoices Add', 'Granular subscription gate for permission: ar-invoices-add', 'accounting', 1094, true),
    ('ar-invoices-edit', 'Ar Invoices Edit', 'Granular subscription gate for permission: ar-invoices-edit', 'accounting', 1095, true),
    ('ar-invoices-delete', 'Ar Invoices Delete', 'Granular subscription gate for permission: ar-invoices-delete', 'accounting', 1096, true),
    ('ar-invoices-tab-overview', 'Ar Invoices Tab Overview', 'Granular subscription gate for permission: ar-invoices-tab-overview', 'accounting', 1097, true),
    ('ar-invoices-view-details', 'Ar Invoices View Details', 'Granular subscription gate for permission: ar-invoices-view-details', 'accounting', 1098, true),
    ('ar-invoices-edit-details', 'Ar Invoices Edit Details', 'Granular subscription gate for permission: ar-invoices-edit-details', 'accounting', 1099, true),
    ('ar-invoices-tab-line-items', 'Ar Invoices Tab Line Items', 'Granular subscription gate for permission: ar-invoices-tab-line-items', 'accounting', 1100, true),
    ('ar-invoices-view-line-items', 'Ar Invoices View Line Items', 'Granular subscription gate for permission: ar-invoices-view-line-items', 'accounting', 1101, true),
    ('ar-invoices-edit-line-items', 'Ar Invoices Edit Line Items', 'Granular subscription gate for permission: ar-invoices-edit-line-items', 'accounting', 1102, true),
    ('ar-invoices-tab-aia', 'Ar Invoices Tab Aia', 'Granular subscription gate for permission: ar-invoices-tab-aia', 'accounting', 1103, true),
    ('ar-invoices-view-aia', 'Ar Invoices View Aia', 'Granular subscription gate for permission: ar-invoices-view-aia', 'accounting', 1104, true),
    ('ar-invoices-edit-aia', 'Ar Invoices Edit Aia', 'Granular subscription gate for permission: ar-invoices-edit-aia', 'accounting', 1105, true),
    ('ar-invoices-export-aia', 'Ar Invoices Export Aia', 'Granular subscription gate for permission: ar-invoices-export-aia', 'accounting', 1106, true),
    ('ar-invoices-send-review', 'Ar Invoices Send Review', 'Granular subscription gate for permission: ar-invoices-send-review', 'accounting', 1107, true),
    ('ar-payments', 'Ar Payments', 'Granular subscription gate for permission: ar-payments', 'accounting', 1108, true),
    ('ar-payments-view', 'Ar Payments View', 'Granular subscription gate for permission: ar-payments-view', 'accounting', 1109, true),
    ('ar-payments-add', 'Ar Payments Add', 'Granular subscription gate for permission: ar-payments-add', 'accounting', 1110, true),
    ('ar-payments-edit', 'Ar Payments Edit', 'Granular subscription gate for permission: ar-payments-edit', 'accounting', 1111, true),
    ('receivables-reports', 'Receivables Reports', 'Granular subscription gate for permission: receivables-reports', 'accounting', 1112, true),
    ('receivables-reports-view', 'Receivables Reports View', 'Granular subscription gate for permission: receivables-reports-view', 'accounting', 1113, true),
    ('payables', 'Payables', 'Granular subscription gate for permission: payables', 'accounting', 1114, true),
    ('payables-dashboard', 'Payables Dashboard', 'Granular subscription gate for permission: payables-dashboard', 'accounting', 1115, true),
    ('payables-dashboard-view', 'Payables Dashboard View', 'Granular subscription gate for permission: payables-dashboard-view', 'accounting', 1116, true),
    ('vendors', 'Vendors', 'Granular subscription gate for permission: vendors', 'accounting', 1117, true),
    ('vendors-view', 'Vendors View', 'Granular subscription gate for permission: vendors-view', 'accounting', 1118, true),
    ('vendors-add', 'Vendors Add', 'Granular subscription gate for permission: vendors-add', 'accounting', 1119, true),
    ('vendors-edit', 'Vendors Edit', 'Granular subscription gate for permission: vendors-edit', 'accounting', 1120, true),
    ('vendors-delete', 'Vendors Delete', 'Granular subscription gate for permission: vendors-delete', 'accounting', 1121, true),
    ('bills', 'Bills', 'Granular subscription gate for permission: bills', 'accounting', 1122, true),
    ('bills-view', 'Bills View', 'Granular subscription gate for permission: bills-view', 'accounting', 1123, true),
    ('bills-add', 'Bills Add', 'Granular subscription gate for permission: bills-add', 'accounting', 1124, true),
    ('bills-edit', 'Bills Edit', 'Granular subscription gate for permission: bills-edit', 'accounting', 1125, true),
    ('bills-delete', 'Bills Delete', 'Granular subscription gate for permission: bills-delete', 'accounting', 1126, true),
    ('bills-approve', 'Bills Approve', 'Granular subscription gate for permission: bills-approve', 'accounting', 1127, true),
    ('banking-credit-cards', 'Banking Credit Cards', 'Granular subscription gate for permission: banking-credit-cards', 'accounting', 1128, true),
    ('credit-cards-view', 'Credit Cards View', 'Granular subscription gate for permission: credit-cards-view', 'accounting', 1129, true),
    ('credit-cards-add', 'Credit Cards Add', 'Granular subscription gate for permission: credit-cards-add', 'accounting', 1130, true),
    ('credit-cards-edit', 'Credit Cards Edit', 'Granular subscription gate for permission: credit-cards-edit', 'accounting', 1131, true),
    ('credit-cards-transactions', 'Credit Cards Transactions', 'Granular subscription gate for permission: credit-cards-transactions', 'accounting', 1132, true),
    ('credit-cards-code', 'Credit Cards Code', 'Granular subscription gate for permission: credit-cards-code', 'accounting', 1133, true),
    ('make-payment', 'Make Payment', 'Granular subscription gate for permission: make-payment', 'accounting', 1134, true),
    ('make-payment-access', 'Make Payment Access', 'Granular subscription gate for permission: make-payment-access', 'accounting', 1135, true),
    ('payment-history', 'Payment History', 'Granular subscription gate for permission: payment-history', 'accounting', 1136, true),
    ('payment-history-view', 'Payment History View', 'Granular subscription gate for permission: payment-history-view', 'accounting', 1137, true),
    ('payment-reports', 'Payment Reports', 'Granular subscription gate for permission: payment-reports', 'accounting', 1138, true),
    ('payment-reports-view', 'Payment Reports View', 'Granular subscription gate for permission: payment-reports-view', 'accounting', 1139, true),
    ('company-files', 'Company Files', 'Granular subscription gate for permission: company-files', 'general', 1140, true),
    ('company-files-view', 'Company Files View', 'Granular subscription gate for permission: company-files-view', 'general', 1141, true),
    ('company-files-upload', 'Company Files Upload', 'Granular subscription gate for permission: company-files-upload', 'general', 1142, true),
    ('company-files-delete', 'Company Files Delete', 'Granular subscription gate for permission: company-files-delete', 'general', 1143, true),
    ('company-contracts', 'Company Contracts', 'Granular subscription gate for permission: company-contracts', 'general', 1144, true),
    ('company-contracts-view', 'Company Contracts View', 'Granular subscription gate for permission: company-contracts-view', 'general', 1145, true),
    ('company-contracts-add', 'Company Contracts Add', 'Granular subscription gate for permission: company-contracts-add', 'general', 1146, true),
    ('company-contracts-edit', 'Company Contracts Edit', 'Granular subscription gate for permission: company-contracts-edit', 'general', 1147, true),
    ('company-permits', 'Company Permits', 'Granular subscription gate for permission: company-permits', 'general', 1148, true),
    ('company-permits-view', 'Company Permits View', 'Granular subscription gate for permission: company-permits-view', 'general', 1149, true),
    ('company-permits-add', 'Company Permits Add', 'Granular subscription gate for permission: company-permits-add', 'general', 1150, true),
    ('company-permits-edit', 'Company Permits Edit', 'Granular subscription gate for permission: company-permits-edit', 'general', 1151, true),
    ('company-insurance', 'Company Insurance', 'Granular subscription gate for permission: company-insurance', 'general', 1152, true),
    ('company-insurance-view', 'Company Insurance View', 'Granular subscription gate for permission: company-insurance-view', 'general', 1153, true),
    ('company-insurance-add', 'Company Insurance Add', 'Granular subscription gate for permission: company-insurance-add', 'general', 1154, true),
    ('company-insurance-edit', 'Company Insurance Edit', 'Granular subscription gate for permission: company-insurance-edit', 'general', 1155, true),
    ('employees', 'Employees', 'Granular subscription gate for permission: employees', 'hr', 1156, true),
    ('employees-view', 'Employees View', 'Granular subscription gate for permission: employees-view', 'hr', 1157, true),
    ('employees-add', 'Employees Add', 'Granular subscription gate for permission: employees-add', 'hr', 1158, true),
    ('employees-edit', 'Employees Edit', 'Granular subscription gate for permission: employees-edit', 'hr', 1159, true),
    ('employees-delete', 'Employees Delete', 'Granular subscription gate for permission: employees-delete', 'hr', 1160, true),
    ('punch-clock-dashboard', 'Punch Clock Dashboard', 'Granular subscription gate for permission: punch-clock-dashboard', 'hr', 1161, true),
    ('punch-clock-dashboard-view', 'Punch Clock Dashboard View', 'Granular subscription gate for permission: punch-clock-dashboard-view', 'hr', 1162, true),
    ('punch-clock-manage', 'Punch Clock Manage', 'Granular subscription gate for permission: punch-clock-manage', 'hr', 1163, true),
    ('timesheets', 'Timesheets', 'Granular subscription gate for permission: timesheets', 'hr', 1164, true),
    ('timesheets-view', 'Timesheets View', 'Granular subscription gate for permission: timesheets-view', 'hr', 1165, true),
    ('timesheets-edit', 'Timesheets Edit', 'Granular subscription gate for permission: timesheets-edit', 'hr', 1166, true),
    ('timesheets-approve', 'Timesheets Approve', 'Granular subscription gate for permission: timesheets-approve', 'hr', 1167, true),
    ('timecard-reports', 'Timecard Reports', 'Granular subscription gate for permission: timecard-reports', 'hr', 1168, true),
    ('timecard-reports-view', 'Timecard Reports View', 'Granular subscription gate for permission: timecard-reports-view', 'hr', 1169, true),
    ('employees-payroll', 'Employees Payroll', 'Granular subscription gate for permission: employees-payroll', 'hr', 1170, true),
    ('employees-payroll-view', 'Employees Payroll View', 'Granular subscription gate for permission: employees-payroll-view', 'hr', 1171, true),
    ('employees-payroll-edit', 'Employees Payroll Edit', 'Granular subscription gate for permission: employees-payroll-edit', 'hr', 1172, true),
    ('employees-performance', 'Employees Performance', 'Granular subscription gate for permission: employees-performance', 'hr', 1173, true),
    ('employees-performance-view', 'Employees Performance View', 'Granular subscription gate for permission: employees-performance-view', 'hr', 1174, true),
    ('employees-reports', 'Employees Reports', 'Granular subscription gate for permission: employees-reports', 'hr', 1175, true),
    ('employees-reports-view', 'Employees Reports View', 'Granular subscription gate for permission: employees-reports-view', 'hr', 1176, true),
    ('messaging', 'Messaging', 'Granular subscription gate for permission: messaging', 'communication', 1177, true),
    ('messages', 'Messages', 'Granular subscription gate for permission: messages', 'communication', 1178, true),
    ('messages-view', 'Messages View', 'Granular subscription gate for permission: messages-view', 'communication', 1179, true),
    ('messages-send', 'Messages Send', 'Granular subscription gate for permission: messages-send', 'communication', 1180, true),
    ('team-chat', 'Team Chat', 'Granular subscription gate for permission: team-chat', 'communication', 1181, true),
    ('team-chat-access', 'Team Chat Access', 'Granular subscription gate for permission: team-chat-access', 'communication', 1182, true),
    ('announcements', 'Announcements', 'Granular subscription gate for permission: announcements', 'communication', 1183, true),
    ('announcements-view', 'Announcements View', 'Granular subscription gate for permission: announcements-view', 'communication', 1184, true),
    ('announcements-create', 'Announcements Create', 'Granular subscription gate for permission: announcements-create', 'communication', 1185, true),
    ('tasks', 'Tasks', 'Granular subscription gate for permission: tasks', 'construction', 1186, true),
    ('tasks-view', 'Tasks View', 'Granular subscription gate for permission: tasks-view', 'construction', 1187, true),
    ('tasks-add', 'Tasks Add', 'Granular subscription gate for permission: tasks-add', 'construction', 1188, true),
    ('tasks-edit', 'Tasks Edit', 'Granular subscription gate for permission: tasks-edit', 'construction', 1189, true),
    ('tasks-delete', 'Tasks Delete', 'Granular subscription gate for permission: tasks-delete', 'construction', 1190, true),
    ('project-tasks', 'Project Tasks', 'Granular subscription gate for permission: project-tasks', 'construction', 1191, true),
    ('project-tasks-view', 'Project Tasks View', 'Granular subscription gate for permission: project-tasks-view', 'construction', 1192, true),
    ('task-deadlines', 'Task Deadlines', 'Granular subscription gate for permission: task-deadlines', 'construction', 1193, true),
    ('task-deadlines-view', 'Task Deadlines View', 'Granular subscription gate for permission: task-deadlines-view', 'construction', 1194, true),
    ('banking', 'Banking', 'Granular subscription gate for permission: banking', 'accounting', 1195, true),
    ('banking-accounts', 'Banking Accounts', 'Granular subscription gate for permission: banking-accounts', 'accounting', 1196, true),
    ('banking-accounts-view', 'Banking Accounts View', 'Granular subscription gate for permission: banking-accounts-view', 'accounting', 1197, true),
    ('banking-accounts-add', 'Banking Accounts Add', 'Granular subscription gate for permission: banking-accounts-add', 'accounting', 1198, true),
    ('banking-accounts-edit', 'Banking Accounts Edit', 'Granular subscription gate for permission: banking-accounts-edit', 'accounting', 1199, true),
    ('chart-of-accounts', 'Chart Of Accounts', 'Granular subscription gate for permission: chart-of-accounts', 'accounting', 1200, true),
    ('chart-of-accounts-view', 'Chart Of Accounts View', 'Granular subscription gate for permission: chart-of-accounts-view', 'accounting', 1201, true),
    ('chart-of-accounts-add', 'Chart Of Accounts Add', 'Granular subscription gate for permission: chart-of-accounts-add', 'accounting', 1202, true),
    ('chart-of-accounts-edit', 'Chart Of Accounts Edit', 'Granular subscription gate for permission: chart-of-accounts-edit', 'accounting', 1203, true),
    ('journal-entries', 'Journal Entries', 'Granular subscription gate for permission: journal-entries', 'accounting', 1204, true),
    ('journal-entries-view', 'Journal Entries View', 'Granular subscription gate for permission: journal-entries-view', 'accounting', 1205, true),
    ('journal-entries-add', 'Journal Entries Add', 'Granular subscription gate for permission: journal-entries-add', 'accounting', 1206, true),
    ('journal-entries-edit', 'Journal Entries Edit', 'Granular subscription gate for permission: journal-entries-edit', 'accounting', 1207, true),
    ('journal-entries-delete', 'Journal Entries Delete', 'Granular subscription gate for permission: journal-entries-delete', 'accounting', 1208, true),
    ('deposits', 'Deposits', 'Granular subscription gate for permission: deposits', 'accounting', 1209, true),
    ('deposits-view', 'Deposits View', 'Granular subscription gate for permission: deposits-view', 'accounting', 1210, true),
    ('deposits-add', 'Deposits Add', 'Granular subscription gate for permission: deposits-add', 'accounting', 1211, true),
    ('print-checks', 'Print Checks', 'Granular subscription gate for permission: print-checks', 'accounting', 1212, true),
    ('print-checks-access', 'Print Checks Access', 'Granular subscription gate for permission: print-checks-access', 'accounting', 1213, true),
    ('reconcile', 'Reconcile', 'Granular subscription gate for permission: reconcile', 'accounting', 1214, true),
    ('reconcile-view', 'Reconcile View', 'Granular subscription gate for permission: reconcile-view', 'accounting', 1215, true),
    ('reconcile-perform', 'Reconcile Perform', 'Granular subscription gate for permission: reconcile-perform', 'accounting', 1216, true),
    ('banking-reports', 'Banking Reports', 'Granular subscription gate for permission: banking-reports', 'accounting', 1217, true),
    ('banking-reports-view', 'Banking Reports View', 'Granular subscription gate for permission: banking-reports-view', 'accounting', 1218, true),
    ('pm-lynk', 'Pm Lynk', 'Granular subscription gate for permission: pm-lynk', 'mobile', 1219, true),
    ('pm-lynk-messages', 'Pm Lynk Messages', 'Granular subscription gate for permission: pm-lynk-messages', 'mobile', 1220, true),
    ('pm-lynk-messages-access', 'Pm Lynk Messages Access', 'Granular subscription gate for permission: pm-lynk-messages-access', 'mobile', 1221, true),
    ('pm-lynk-delivery-tickets', 'Pm Lynk Delivery Tickets', 'Granular subscription gate for permission: pm-lynk-delivery-tickets', 'mobile', 1222, true),
    ('pm-lynk-delivery-tickets-access', 'Pm Lynk Delivery Tickets Access', 'Granular subscription gate for permission: pm-lynk-delivery-tickets-access', 'mobile', 1223, true),
    ('pm-lynk-receipt-scanner', 'Pm Lynk Receipt Scanner', 'Granular subscription gate for permission: pm-lynk-receipt-scanner', 'mobile', 1224, true),
    ('pm-lynk-receipt-scanner-access', 'Pm Lynk Receipt Scanner Access', 'Granular subscription gate for permission: pm-lynk-receipt-scanner-access', 'mobile', 1225, true),
    ('pm-lynk-tasks', 'Pm Lynk Tasks', 'Granular subscription gate for permission: pm-lynk-tasks', 'mobile', 1226, true),
    ('pm-lynk-tasks-access', 'Pm Lynk Tasks Access', 'Granular subscription gate for permission: pm-lynk-tasks-access', 'mobile', 1227, true),
    ('pm-lynk-safety', 'Pm Lynk Safety', 'Granular subscription gate for permission: pm-lynk-safety', 'mobile', 1228, true),
    ('pm-lynk-safety-access', 'Pm Lynk Safety Access', 'Granular subscription gate for permission: pm-lynk-safety-access', 'mobile', 1229, true),
    ('pm-lynk-directory', 'Pm Lynk Directory', 'Granular subscription gate for permission: pm-lynk-directory', 'mobile', 1230, true),
    ('pm-lynk-directory-access', 'Pm Lynk Directory Access', 'Granular subscription gate for permission: pm-lynk-directory-access', 'mobile', 1231, true),
    ('pm-lynk-bill-coding', 'Pm Lynk Bill Coding', 'Granular subscription gate for permission: pm-lynk-bill-coding', 'mobile', 1232, true),
    ('pm-lynk-bill-coding-access', 'Pm Lynk Bill Coding Access', 'Granular subscription gate for permission: pm-lynk-bill-coding-access', 'mobile', 1233, true),
    ('settings', 'Settings', 'Granular subscription gate for permission: settings', 'general', 1234, true),
    ('company-settings', 'Company Settings', 'Granular subscription gate for permission: company-settings', 'general', 1235, true),
    ('company-settings-view', 'Company Settings View', 'Granular subscription gate for permission: company-settings-view', 'general', 1236, true),
    ('company-settings-edit', 'Company Settings Edit', 'Granular subscription gate for permission: company-settings-edit', 'general', 1237, true),
    ('organization-management', 'Organization Management', 'Granular subscription gate for permission: organization-management', 'general', 1238, true),
    ('organization-management-access', 'Organization Management Access', 'Granular subscription gate for permission: organization-management-access', 'general', 1239, true),
    ('user-settings', 'User Settings', 'Granular subscription gate for permission: user-settings', 'general', 1240, true),
    ('user-settings-view', 'User Settings View', 'Granular subscription gate for permission: user-settings-view', 'general', 1241, true),
    ('user-settings-edit', 'User Settings Edit', 'Granular subscription gate for permission: user-settings-edit', 'general', 1242, true),
    ('user-settings-edit-email', 'User Settings Edit Email', 'Granular subscription gate for permission: user-settings-edit-email', 'general', 1243, true),
    ('user-settings-change-password', 'User Settings Change Password', 'Granular subscription gate for permission: user-settings-change-password', 'general', 1244, true),
    ('user-settings-permissions', 'User Settings Permissions', 'Granular subscription gate for permission: user-settings-permissions', 'general', 1245, true),
    ('punch-clock-settings', 'Punch Clock Settings', 'Granular subscription gate for permission: punch-clock-settings', 'hr', 1246, true),
    ('punch-clock-settings-view', 'Punch Clock Settings View', 'Granular subscription gate for permission: punch-clock-settings-view', 'hr', 1247, true),
    ('punch-clock-settings-edit', 'Punch Clock Settings Edit', 'Granular subscription gate for permission: punch-clock-settings-edit', 'hr', 1248, true),
    ('pm-lynk-settings', 'Pm Lynk Settings', 'Granular subscription gate for permission: pm-lynk-settings', 'mobile', 1249, true),
    ('pm-lynk-settings-view', 'Pm Lynk Settings View', 'Granular subscription gate for permission: pm-lynk-settings-view', 'mobile', 1250, true),
    ('pm-lynk-settings-edit', 'Pm Lynk Settings Edit', 'Granular subscription gate for permission: pm-lynk-settings-edit', 'mobile', 1251, true),
    ('subscription-settings', 'Subscription Settings', 'Granular subscription gate for permission: subscription-settings', 'general', 1252, true),
    ('subscription-settings-view', 'Subscription Settings View', 'Granular subscription gate for permission: subscription-settings-view', 'general', 1253, true),
    ('subscription-settings-edit', 'Subscription Settings Edit', 'Granular subscription gate for permission: subscription-settings-edit', 'general', 1254, true),
    ('notification-settings', 'Notification Settings', 'Granular subscription gate for permission: notification-settings', 'general', 1255, true),
    ('notification-settings-view', 'Notification Settings View', 'Granular subscription gate for permission: notification-settings-view', 'general', 1256, true),
    ('notification-settings-edit', 'Notification Settings Edit', 'Granular subscription gate for permission: notification-settings-edit', 'general', 1257, true),
    ('security-settings', 'Security Settings', 'Granular subscription gate for permission: security-settings', 'general', 1258, true),
    ('security-settings-view', 'Security Settings View', 'Granular subscription gate for permission: security-settings-view', 'general', 1259, true),
    ('security-settings-edit', 'Security Settings Edit', 'Granular subscription gate for permission: security-settings-edit', 'general', 1260, true)
)
INSERT INTO public.feature_modules (key, name, description, category, sort_order, is_active)
SELECT key, name, description, category, sort_order, is_active FROM new_features
ON CONFLICT (key) DO UPDATE
SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  is_active = EXCLUDED.is_active;
